### PR TITLE
Modified paths.js to handle multiple subpaths

### PR DESCRIPTION
**Pull request by yowzadave**
A very minor adjustment: for my current project, I wanted to create paths that had multiple subpaths. While supported by SVG, this was breaking on using the .points() or .connect() functions in paths-js.

This resolves issue #51.

### CODE REVIEW

**Comment by andreaferretti** [comment]
Hi @yowzadave, thank you very much for your contribution!

I am going to merge this - would you mind adding a few lines about the support for multiple paths and the `translate` and `rotate` methods to [this page](https://github.com/andreaferretti/paths-js/wiki/Low-level-API)? (Is it editable by you?)

I am going to release a new version with your new additions. By the way, what is the `main` parameter in package.json needed for?

**Comment by andreaferretti** [comment]
Just published version 0.4.6

**Comment by yowzadave** [comment]
Ah, I was only using the `main` parameter to include my github repository as a dependency in another project. You can safely ignore that change.

I'd be happy to document the additions to that page, but at the moment it is not editable for me.

I was also meaning to add `scale` and `shear` functions—now that the affine transformation logic is there, it would be a quick addition.

**Comment by andreaferretti** [comment]
I have added you as a collaborator, so you should be able to edit the wiki page as soon as you accept.

Please, for code modifications, use PRs anyway - it is easier for me to keep track and review what is happening.

I agree that it would be nice to add scale and shear as well - maybe also move the affine transform logic into the `geom.js` module so that it can be tested on its own.

I don't want to burden you with things to do anyway - if at some point you decide that you don't have time and there are still tests or documentation to add, just ping me and I will take care of what's missing

**Pull request merged**
