### PR TITLE
Remove build files from repo, add grunt task on npm postinstall

### PR DESCRIPTION
**Pull request by jvanveen**
Hey there!

I'm trying to include paths-js in my browserify/gulp workflow and added a grunt build task to npm postinstall. I also removed build files from the repo. Let me know if this pull request needs some more work, and i'll modify it until it's ok for a merge! :)

cheers,

Jeroen

### CODE REVIEW

**Comment by andreaferretti** [comment]
I am not sure what is exactly the purpose of this pull request - could you elaborate?

If I understand correctly, the point would be to remove the built files and rely on NPM to generate them on the fly. This, however, creates some issuesfor people that use a different workflow.

For instance, my main workflow uses Bower and Require.js. For this, I need the built AMD files to be present in the git directory. Other users may rely on the global build and just download that file from github, and again they would not be well served if I required them to install and use NPM.

On the other hand, I regularly publish the output of the dist folder on NPM - you can find it [here](https://www.npmjs.com/package/paths-js). So I think that you should be able to use Paths with Browserify just by adding `"paths-js": "0.3.0"` in your package.json - no need to point at this github repository.

Let me know if this works for you: I am very interested in keeping compatibility both with Bower and with NPM, so your feedback is vvery much appreciated!

**Comment by jvanveen** [comment]
Hi,

I figured that buildfiles are not needed in the repo and that it's easier to generate these on install, but I didn't know that bower doesn't support running post_install scripts on install! So I guess these buildfiles can't be deleted then. I'm using npm/browserify myself to install and use paths-js and import like:

var Graph = require('paths-js/dist/node/graph')

**Comment by andreaferretti** [comment]
Not only that, but adding a post-install script would require every user to have - say - coffeescript and grunt installed, which may very well not be the case.

Still, I think you are using the wrong address to retrieve Paths-js on NPM. It is published, so you should just have `"paths-js": "0.3.0"` in your package.json and it will be retrieved from the official NPM repositories. In particular, you should not point directly to this git repository. If you do this, you should be able to import it directly - i.e. it will be under `node_modules/paths-js` and not under `node_modules/paths-js/dist/node`

**Comment by jvanveen** [comment]
From npm perspective, it might be easier to have the same file structure in github as on npm, so people can npm install bleeding edge from github directly, while maintaining the same require('paths-js/module'). 
How about if grunt writes the commonjs to node_modules/paths-js/lib directory(require('paths-js/lib/graph')) and do a grunt build as post_install script that parses the coffeescript to ./lib?

It's frustrating that bower doesn't support post_install scripts from the package, but there might be another way(http://blog.stackfull.com/2013/05/publishing-bower-components/). 

The author suggests to keep the build directory as a seperate git submodule. That would also produce smaller commits. What do you think?

**Comment by andreaferretti** [comment]
I am not sure: I keep NPM updated any time I do something new, and moreover this is still an issue for people that do not use grunt or coffeescript. Not to mention people that do not use Node or build scripts at all and just want to download a single file to include in the page.

Frankly I am quite happy with the way it is handled right now. The only very minor downside is for me in that I have to double publish every update, but it is really a small annoyance

**Pull request closed without merging**
